import {chromium} from 'playwright';
import {build} from 'esbuild';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
await mkdir('.local',{recursive:true});await mkdir('artifacts',{recursive:true});
const profile=await mkdtemp(resolve('.local/browser-test-'));
const extension=resolve('dist');
const context=await chromium.launchPersistentContext(profile,{channel:'chromium',executablePath:process.env.WSF_TEST_CHROME,headless:true,args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`]});
const log=[];const errors=[];
try{
  context.on('page',page=>page.on('pageerror',e=>errors.push(e.message)));
  const worker=context.serviceWorkers()[0]??await context.waitForEvent('serviceworker',{timeout:15000});
  const id=new URL(worker.url()).host;
  const card=(authorId,postId,text)=>`<article tabindex="0" style="background:white;padding:16px;margin:10px;border:1px solid #ddd"><div><header><a aria-label="测试账号" href="https://weibo.com/u/${authorId}">测试账号</a> <a href="https://weibo.com/${authorId}/${postId}">今天</a></header><div class="wbpro-feed-content"><div class="wbpro-feed-ogText"><div class="_wbtext_fixture_1">${text}</div></div></div></div><footer><button>原生评论</button></footer></article>`;
  const html=`<!doctype html><html><head><meta charset="utf-8"><style>body{background:#eee;margin:0 auto;max-width:700px;font:16px/1.7 system-ui}</style></head><body><h1>微博原网页 · 测试样本</h1>${card('1249424622','Reply1','回复 @某人：谢谢！')}${card('2173738960','Keep1','人生哲理与足球世界杯')}${card('2820792015','Wang1','人生总有风雨')}${card('999999999','Other1','谢谢')}</body></html>`;
  await context.route('https://weibo.com/**',route=>route.fulfill({contentType:'text/html',body:html}));
  const page=await context.newPage();await page.goto('https://weibo.com/');
  await page.locator('article').first().locator('[data-wsf-control="bar"]:not([data-wsf-status])').waitFor();
  assert.equal(await page.locator('article[data-wsf-state="collapsed"]').count(),1);
  assert.match(await page.locator('[data-wsf-control="bar"]:not([data-wsf-status])').first().innerText(),/建议折叠/);log.push('Default Shadow suggests for target accounts and directly folds non-target accounts.');
  await page.locator('article').nth(1).locator('[data-wsf-control="bar"]:not([data-wsf-status])').waitFor();
  assert.match(await page.locator('article').nth(1).innerText(),/保留/);
  log.push('Retention labels appear with debug disabled.');
  const outsideCard=page.locator('article').nth(3);
  assert.equal(await outsideCard.locator('.wbpro-feed-content').isVisible(),false);
  assert.match(await outsideCard.innerText(),/已折叠：非目标账号，自动折叠/);
  assert.doesNotMatch(await outsideCard.innerText(),/建议/);
  await outsideCard.getByRole('button',{name:'展开',exact:true}).click();
  assert.equal(await outsideCard.locator('.wbpro-feed-content').isVisible(),true);
  log.push('Non-target folding has no suggestion label and can be expanded in Shadow.');
  const shadowBar=page.locator('article').first().locator('[data-wsf-control="bar"]:not([data-wsf-status])');
  await shadowBar.getByRole('button',{name:'应折叠',exact:true}).click();
  await page.waitForSelector('article[data-wsf-state="collapsed"]');
  await page.waitForFunction(()=>document.querySelector('article [role="status"]')?.textContent.includes('已记录：应折叠'));
  await shadowBar.getByRole('button',{name:'应保留',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('article[data-wsf-state="collapsed"]')&&document.querySelector('article [role="status"]')?.textContent.includes('已记录：应保留'));
  log.push('Shadow feedback immediately folds/restores the card and confirms successful persistence.');
  await page.reload();await page.locator('article').first().locator('[data-wsf-control="bar"]:not([data-wsf-status])').waitFor();
  const options=await context.newPage();await options.goto(`chrome-extension://${id}/options.html`);
  await options.waitForFunction(()=>document.querySelector('#endpoint').value.includes('typesafe.ai'));
  await options.screenshot({path:'artifacts/settings-preview.png',fullPage:true});
  await options.selectOption('#mode','active');await options.click('button[type="submit"]');await options.waitForFunction(()=>document.querySelector('#status').textContent==='已保存');
  await page.locator('article').first().locator('[data-wsf-control="bar"]:not([data-wsf-status])').waitFor();
  await page.waitForFunction(()=>document.querySelectorAll('article[data-wsf-state="collapsed"]').length===2);
  assert.equal(await page.locator('article[data-wsf-state="collapsed"]').count(),2);
  assert.equal(await page.locator('article').nth(1).getAttribute('data-wsf-state'),null);
  assert.equal(await page.locator('article').first().locator('.wbpro-feed-content').isVisible(),false);
  await page.screenshot({path:'artifacts/folded-preview.png',fullPage:true});
  await page.locator('[data-wsf-control="bar"]:not([data-wsf-status])').first().getByRole('button',{name:'展开',exact:true}).click();
  assert.equal(await page.locator('article').first().locator('.wbpro-feed-content').isVisible(),true);log.push('Active applies local rule; original card restores on click.');
  const pageId=await worker.evaluate(async()=>{const tabs=await chrome.tabs.query({url:'https://weibo.com/*'});return tabs[0].id;});
  const command=type=>worker.evaluate(async({type,pageId})=>chrome.tabs.sendMessage(pageId,{type}),{type,pageId});
  assert.equal((await command('pageStats')).data.suggestedCollapse,1);
  await command('expandAll');
  await page.evaluate(html=>document.body.insertAdjacentHTML('beforeend',html),card('1249424622','Reply2','回复 @某人：谢谢'));
  await command('rescan');
  await page.waitForFunction(()=>document.querySelectorAll('article').length===5);
  await page.waitForFunction(()=>!document.querySelector('[data-wsf-state="collapsed"]'));
  assert.equal((await command('pageStats')).data.paused,true);
  await command('expandAll');await page.waitForSelector('article[data-wsf-state="collapsed"]');
  assert.equal(await page.locator('article').first().getAttribute('data-wsf-state'),null);log.push('Expand-all survives rescan and new cards; per-post expand survives resume.');
  await page.locator('article').last().locator('[data-wsf-control="bar"]:not([data-wsf-status])').getByRole('button',{name:'应保留',exact:true}).click();
  await options.waitForFunction(async()=>{const r=await chrome.runtime.sendMessage({type:'exportFeedback'});return r.data?.some(row=>row.label==='KEEP');});
  const feedback=await options.evaluate(async()=>{const r=await chrome.runtime.sendMessage({type:'exportFeedback'});return r.data;});
  assert.ok(feedback.some(r=>r.label==='KEEP'));assert.equal(feedback[0].text,undefined);log.push('Feedback persists without storing text by default.');
  await page.evaluate(()=>{document.querySelector('article ._wbtext_fixture_1').textContent='回复 @某人：公司发布了重要经营数据';});
  await command('rescan');
  await options.uncheck('#enabled');await options.click('button[type="submit"]');await options.waitForFunction(()=>document.querySelector('#status').textContent==='已保存');
  await page.waitForFunction(()=>document.querySelectorAll('[data-wsf-control="bar"]:not([data-wsf-status])').length===0);
  assert.equal(await page.locator('[data-wsf-state]').count(),0);log.push('Disabling restores all cards and removes controls.');
  const stats=await options.evaluate(async()=>{const r=await chrome.runtime.sendMessage({type:'getSettings'});return r.data.stats;});assert.equal(stats.calls,0);
  // Content-script reads must not expose storage.local: evaluate in the actual isolated world.
  const cdp=await context.newCDPSession(page);const worlds=[];cdp.on('Runtime.executionContextCreated',e=>worlds.push(e.context));await cdp.send('Runtime.enable');
  const contentWorld=worlds.find(w=>w.origin===`chrome-extension://${id}`);
  if(!contentWorld)throw Error('Content script isolated world not found');
  const storage=await cdp.send('Runtime.evaluate',{contextId:contentWorld.id,expression:'chrome.storage.local.get(null).then(()=>"exposed",()=>"restricted")',awaitPromise:true,returnByValue:true});
  assert.equal(storage.result.value,'restricted');log.push('storage.local is restricted from the content-script world.');
  await options.check('#enabled');await options.check('#debug');await options.click('button[type="submit"]');
  const protectedBar=page.locator('article').nth(1).locator('[data-wsf-control="bar"]:not([data-wsf-status])');
  await protectedBar.waitFor();await protectedBar.evaluate(element=>element.remove());
  await protectedBar.waitFor();assert.match(await protectedBar.innerText(),/语义服务未配置/);
  log.push('Debug retention labels recover after the site removes injected controls.');
  await options.selectOption('#mode','shadow');await options.click('button[type="submit"]');
  assert.equal(await options.isChecked('#namedPeople'),true);
  await page.evaluate(html=>document.body.insertAdjacentHTML('beforeend',html),card('2173738960','People1','林园与董宝珍谈价值投资'));
  const peopleCard=page.locator('article').last();
  await peopleCard.locator('[data-wsf-control="bar"]:not([data-wsf-status])').waitFor();
  assert.match(await peopleCard.innerText(),/建议折叠：通用规则：涉及林园、董宝珍/);
  assert.equal(await peopleCard.getAttribute('data-wsf-state'),null);
  assert.equal(await peopleCard.locator('.wbpro-feed-content').isVisible(),true);
  await options.uncheck('#namedPeople');await options.click('button[type="submit"]');
  await page.waitForFunction(()=>!document.querySelector('article:last-of-type [data-wsf-control="bar"]:not([data-wsf-status])')?.textContent.includes('涉及林园'));
  await options.reload();await options.waitForFunction(()=>document.querySelector('#endpoint').value.includes('typesafe.ai'));
  assert.equal(await options.isChecked('#namedPeople'),false);
  log.push('Named-person rule suggests collapse in Shadow without model calls; disabling persists and removes the suggestion.');
  await page.evaluate(html=>document.body.insertAdjacentHTML('beforeend',html),card('888888888','Pushed1','自动推荐的其他博主'));
  const pushed=page.locator('article').last();
  await pushed.locator('[data-wsf-control="bar"]:not([data-wsf-status])').waitFor();
  assert.equal(await pushed.getAttribute('data-wsf-state'),'collapsed');
  assert.doesNotMatch(await pushed.innerText(),/建议/);
  await options.uncheck('#collapseOtherAccounts');await options.click('button[type="submit"]');
  await page.waitForFunction(()=>!document.querySelector('article:last-of-type').hasAttribute('data-wsf-state'));
  await options.reload();await options.waitForFunction(()=>document.querySelector('#endpoint').value.includes('typesafe.ai'));
  assert.equal(await options.isChecked('#collapseOtherAccounts'),false);
  await page.reload();await page.locator('article').first().locator('[data-wsf-control="bar"]:not([data-wsf-status])').waitFor();
  assert.equal(await page.locator('article').nth(3).getAttribute('data-wsf-state'),null);
  await options.check('#collapseOtherAccounts');await options.click('button[type="submit"]');
  await page.waitForFunction(()=>document.querySelectorAll('article')[3].getAttribute('data-wsf-state')==='collapsed');
  log.push('New recommendations fold in Shadow; the scope toggle restores content and persists through refresh.');
  const repost=card('2820792015','RepostEmpty','').replace('<div class="_wbtext_fixture_1"></div>','').replace('</article>','<div class="retweet"><div class="wbpro-feed-reText"><div class="_wbtext_fixture_1">转发原文</div></div></div></article>');
  await page.evaluate(html=>document.body.insertAdjacentHTML('beforeend',html),repost);
  await page.locator('article').last().scrollIntoViewIfNeeded();
  await page.locator('article').last().locator('[data-wsf-control="bar"]:not([data-wsf-status])').waitFor();
  assert.match(await page.locator('article').last().innerText(),/保留/);
  log.push('Reposts without an added comment receive a final banner.');
  // Exercise native fetch in the extension worker: Node mocks do not enforce Web IDL receivers.
  const providerBundle=await build({entryPoints:['src/classifier/jev-provider.ts'],bundle:true,write:false,format:'iife',globalName:'WSFProviderTest',target:'chrome120'});
  const fixtureUrl='data:application/json,'+encodeURIComponent(JSON.stringify({model:'fixture',answers:{social_interaction:{type:'noul',noul:.95}}}));
  const nativeResult=await worker.evaluate(providerBundle.outputFiles[0].text+`; new WSFProviderTest.JevProvider(${JSON.stringify(fixtureUrl)},'test-only','fixture',1000).classify({text:'test',repostText:'',visibleContext:'',decisions:['social_interaction']},new AbortController().signal)`);
  assert.equal(nativeResult.scores.social_interaction,.95);log.push('Provider completes a request using native fetch inside the Chrome extension worker.');
  assert.deepEqual(errors,[]);
  await writeFile('artifacts/browser-test-report.json',JSON.stringify({date:new Date().toISOString(),browser:context.browser()?.version(),checks:log,modelCalls:stats.calls,errors},null,2));
  console.log(JSON.stringify({passed:log.length,checks:log,errors}));
}finally{await context.close();await rm(profile,{recursive:true,force:true});}
